trying to lighthouse tests to work

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -5,48 +5,52 @@ on:
     branches: "*"
   workflow_dispatch:
 
+
 jobs:
-  build:
+  build-and-test:
     runs-on: ubuntu-latest
-    container:
-      image: ubuntu:latest
-      options: --cpus 2 --memory 4G --user root
     env:
+      tests_failed: ''
       SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
       NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
       NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.SANITY_API_DATASET }} 
       SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }} 
       SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
-      tests_failed: '' 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
+      - name: Setup Node
+        uses: actions/setup-node@v2
         with:
-          node-version: "18.x"
+          node-version: '18.x'
 
       - name: Install dependencies
         run: |
-          apt-get update
-          apt-get install -y libgbm-dev         
           npm ci
-          npx playwright install chromium
-          npm install -g lighthouse chrome-launcher axe-core chromium wait-on
-          npx playwright install-deps  
           npm run build --turbo
+          
+
+      - name: Setup Playwright
+        uses: microsoft/playwright-github-action@v1
+
+      - name: Install Playwright browsers
+        run: npx playwright install
+
+      - name: Setup XVFB
+        run: sudo apt-get install -y xvfb
       - name: Start the application
         run: |
           export DISPLAY=:1
           npm run start 2>&1 > app.log &
-          npx wait-on --timeout 30000 http://localhost:3000 ||  echo "tests_failed=true" >> $GITHUB_ENV
-      - name: Print tests_failed
-        run: echo "tests_failed=$tests_fail
-      - name: Run Playwright tests
+          npx wait-on --timeout 30000 http://localhost:3000 || (cat app.log && exit 1)
+      - name: Run tests
         env:
           PLAYWRIGHT_CLI_EXIT_ON_FIRST_FAILURE: '1'
-        run: npx playwright test --config=playwright.config.js 
+        run: npx playwright test--config=playwright.config.js || echo "tests_failed=true" >> $GITHUB_ENV
+
+      - name: Print tests_failed
+        run: echo "tests_failed=$tests_failed"
 
       - name: Install jq
         run: sudo apt-get install jq
@@ -61,6 +65,8 @@ jobs:
             test-results/
             **/*.mp4
             **/*.png
+
       - name: Exit with failure if tests failed
         if: env.tests_failed == 'true'
         run: exit 1
+
