Update playwright.yml
trying to fix workflow

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -47,16 +47,14 @@ jobs:
           export DISPLAY=:1
           npm run start 2>&1 > app.log &
           npx wait-on --timeout 30000 http://localhost:3000 || (cat app.log && exit 1)
-
       - name: Run Playwright tests
-        run: npx playwright test --config=playwright.config.js || true
+        run: npx playwright test --config=playwright.config.js || echo "Tests failed, generating Lighthouse report for failed tests."
 
       - name: Generate Lighthouse Report
         run: |
           lighthouse http://localhost:3000 --output html --output-path ./reports/report.html --chrome-flags="--headless --no-sandbox --disable-gpu"
-
       - name: Upload report, screenshots and videos of failed tests
         uses: actions/upload-artifact@v3
         with:
           name: test-results
-          path: test-results
+          path: ./test-results
