trying to lighthouse tests to work

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -16,7 +16,8 @@ jobs:
       NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
       NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.SANITY_API_DATASET }} 
       SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }} 
-      SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }} 
+      SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
+      tests_failed: '' 
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -39,15 +40,27 @@ jobs:
         run: |
           export DISPLAY=:1
           npm run start 2>&1 > app.log &
-          npx wait-on --timeout 30000 http://localhost:3000 || (cat app.log && exit 1)
+          npx wait-on --timeout 30000 http://localhost:3000 ||  echo "tests_failed=true" >> $GITHUB_ENV
+      - name: Print tests_failed
+        run: echo "tests_failed=$tests_fail
       - name: Run Playwright tests
-        run: npx playwright test --config=playwright.config.js
+        env:
+          PLAYWRIGHT_CLI_EXIT_ON_FIRST_FAILURE: '1'
+        run: npx playwright test --config=playwright.config.js 
 
-      - name: Generate Lighthouse Report
-        run: |
-          lighthouse http://localhost:3000 --output html --output-path ./reports/report.html --chrome-flags="--headless --no-sandbox --disable-gpu"
-      - name: Upload report, screenshots and videos of failed tests
+      - name: Install jq
+        run: sudo apt-get install jq
+
+      - name: Archive Lighthouse report, videos, and screenshots
+        if: env.tests_failed == 'true'
         uses: actions/upload-artifact@v3
         with:
-          name: test-results
-          path: ./test-results
+          name: test-artifacts
+          path: |
+            lighthouse-report.json
+            test-results/
+            **/*.mp4
+            **/*.png
+      - name: Exit with failure if tests failed
+        if: env.tests_failed == 'true'
+        run: exit 1
